config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :experiences

  resources :types

  resources :skills

  resources :categories

  resources :contacts, only: [:index, :create], :path => "contact"
  
  if Settings.registration
    devise_for :users, controllers: {registrations: "registrations"}
  else
    devise_for :users, :skip => [:registrations], controllers: {registrations: "registrations"}
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
  end

  match '/admin', :to => 'pages#admin', :via => [:get, :post]  
  match '/home', :to => 'pages#home', :via => [:get, :post]
  
  root to: 'pages#home'
  
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  
  

end

app/views/layouts/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  ga('create', 'UA-55637763-1', 'bottein.fr');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

app/views/layouts/_footer.html.haml
%footer
  .container
    %small= t('footer.text')

app/views/layouts/_navbar.html.haml
%nav.navbar.fixed-top.navbar-shadow.navbav-primary{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %span.navbar-brand= t("menu.application")

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{:class => ("active" if current_page?(root_path))}= link_to t('menu.home'), root_path
        %li{:class => ("active" if controller.controller_name == 'experiences')}= link_to t('menu.experiences'), experiences_path
        %li{:class => ("active" if controller.controller_name == 'projects')}= link_to t('menu.projects'), projects_path
        %li{:class => ("active" if controller.controller_name == 'skills')}= link_to t('menu.skills'), skills_path
        %li{:class => ("active" if controller.controller_name == 'contacts')}= link_to t('menu.contact'), contacts_path
        - if can? :update, Category or can? :destroy, Category or can? :update, Type or can? :destroy, Type
          %li{:class => ("active" if current_page?(admin_path) || controller.controller_name == 'categories' || controller.controller_name == 'types')}= link_to t('menu.admin'), admin_path
          
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown{:class => ("active" if controller.controller_name == 'registrations' || controller.controller_name == 'sessions')}
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
            = t('menu.account')
            %b.caret
          %ul.dropdown-menu 
            - if user_signed_in?
              %li= link_to current_user.email.to_s, edit_user_registration_path
              -# %li= link_to t('devise.registrations.edit.edit_profile'), edit_user_registration_path
              %li= link_to t('devise.sessions.new.logout'), destroy_user_session_path, method: :delete
            - else
              - if Settings.registration
                %li= link_to t('devise.registrations.new.sign_up'), new_user_registration_path
              %li= link_to t('devise.sessions.new.sign_in'), new_user_session_path  
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i{:class => flag(I18n.locale)}
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            - I18n.available_locales.each do |lang|            
              %li
                %a{:href => change_locale_path(lang)}
                  %i{:class => flag(lang)}
                  = t('menu.languages.' + lang.to_s)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    
  %body.fixed-top-body
    = render 'layouts/navbar'
    .scrool
      .container
        - if notice
          .alert.alert-dismissable.alert-success
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = notice
        - if alert
          .alert.alert-dismissable.alert-danger
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = alert
        - if !subtitle.blank?
          %h1.page-header= subtitle
        = yield
    %i.icon.icon-material-settings    
    = render 'layouts/footer' 
    = render 'layouts/analytics' if Rails.env.production?
    :javascript
    $(function() {
        $.material.init();
    });
    